# Configuración BGP para FRR
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp default ipv4-unicast
 distance bgp 20 200 200
 !
 address-family ipv4 unicast
  network 172.20.0.0/16
  network 172.21.0.0/16
  network 172.22.0.0/16
  network 172.23.0.0/16
  neighbor 172.20.0.2 remote-as 65001
  neighbor 172.21.0.2 remote-as 65002
  neighbor 172.22.0.2 remote-as 65003
  neighbor 172.23.0.2 remote-as 65004
 exit-address-family